import { StaleRevision, ValidationError, ProviderError } from "./errors.mjs";
import { cloneState, newId, nowUtc, validateState } from "./model.mjs";
import { buildProjection, findRuntime } from "./projection.mjs";
import { CONTRACT_VERSION, invokeProvider, providerLabel } from "./provider.mjs";
import { requirePrincipal, userEvidence } from "./semantics.mjs";

export function startRuntime(state,principal,scope,{timestamp=nowUtc()}={}){requirePrincipal(state,principal);if(typeof scope!=="string"||!scope.trim())throw new ValidationError("active scope must be non-empty");const candidate=cloneState(state),previous=latestRuntime(candidate);let recovery;if(!previous)recovery={previous_runtime:null,current_runtime:null,gap_kind:"initial_start",last_durable_observation_at:null,clean_stop_at:null,restart_at:timestamp,ember_cognition_during_interval:"not_applicable",external_changes_during_interval:"unknown"};else if(previous.clean_stop_at!==null)recovery={previous_runtime:previous.runtime_id,current_runtime:null,gap_kind:"known_clean_stop_interval",last_durable_observation_at:previous.last_durable_observation_at,clean_stop_at:previous.clean_stop_at,restart_at:timestamp,ember_cognition_during_interval:"none_in_supported_runtime",external_changes_during_interval:"unknown"};else{recovery={previous_runtime:previous.runtime_id,current_runtime:null,gap_kind:"uncertain_interruption_boundary",last_durable_observation_at:previous.last_durable_observation_at,clean_stop_at:null,restart_at:timestamp,ember_cognition_during_interval:"unknown_after_last_durable_observation",external_changes_during_interval:"unknown"};for(const cognition of candidate.operations.cognition_episodes)if(cognition.runtime_id===previous.runtime_id&&cognition.status==="started")cognition.status="outcome_unknown";}
  const runtimeId=newId("runtime");recovery.current_runtime=runtimeId;candidate.operations.runtime_episodes.push({runtime_id:runtimeId,principal,active_scope:scope,started_at:timestamp,last_durable_observation_at:timestamp,clean_stop_at:null,stop_reason:null,recovery_account:recovery});validateState(candidate);return {state:candidate,runtimeId};}
export function stopRuntime(state,runtimeId,{reason,timestamp=nowUtc()}={}){const candidate=cloneState(state),runtime=findRuntime(candidate,runtimeId);if(runtime.clean_stop_at!==null)throw new ValidationError("runtime is already stopped");runtime.last_durable_observation_at=timestamp;runtime.clean_stop_at=timestamp;runtime.stop_reason=reason;validateState(candidate);return candidate;}
export async function runCognition(store,state,{runtimeId,principal,scope,text,command,arguments_:args=[],timeoutSeconds,output=process.stdout,purpose="ordinary",explainIds=[],provider=invokeProvider,hooks={}}){
  requirePrincipal(state,principal);const timestamp=nowUtc(),projection=buildProjection(state,{principal,scope,currentInput:text,currentTime:timestamp,runtimeId,purpose,explainIds}),cognitionId=newId("cognition"),label=providerLabel(command),started=cloneState(state),input=userEvidence(started,principal,scope,text,{timestamp});findRuntime(started,runtimeId).last_durable_observation_at=timestamp;started.operations.cognition_episodes.push({cognition_id:cognitionId,runtime_id:runtimeId,principal,active_scope:scope,provider_label:label,purpose,started_at:timestamp,last_durable_observation_at:timestamp,status:"started",selected_meaning_ids:projection.selection.meaning_ids,selected_evidence_ids:projection.selection.evidence_ids,used_meaning_ids:[],input_evidence_id:input.evidence_id,expression_evidence_id:null,delivery_status:"not_attempted"});state=await store.commit(state.revision,started);
  const request={contract_version:CONTRACT_VERSION,cognition_id:cognitionId,projection,input:{text}};let result;
  try{result=await provider(command,args,request,{timeoutSeconds});}
  catch(error){if(!(error instanceof ProviderError))throw error;const current=await store.load();if(current.revision!==state.revision)throw new StaleRevision("canonical revision changed during provider failure",{cause:error});const failed=cloneState(current),cognition=findCognition(failed,cognitionId),at=nowUtc();cognition.status=error.outcome;cognition.last_durable_observation_at=at;findRuntime(failed,runtimeId).last_durable_observation_at=at;state=await store.commit(current.revision,failed);return {state,providerFailure:error.message,cognitionId};}
  const current=await store.load();if(current.revision!==state.revision)throw new StaleRevision("canonical revision changed during provider call");const completed=cloneState(current),cognition=findCognition(completed,cognitionId),expressionId=newId("evidence"),at=nowUtc();completed.evidence.push({evidence_id:expressionId,source_role:"ember_expression_via_provider",source_actor:"ember",asserted_principal:principal,occurred_at:at,observed_at:at,derived_from_evidence_ids:[],scope,payload_mode:"descriptor_only",cognition_id:cognitionId,provider_label:label});Object.assign(cognition,{status:"completed",last_durable_observation_at:at,used_meaning_ids:result.used_meaning_ids,expression_evidence_id:expressionId,delivery_status:"pending"});findRuntime(completed,runtimeId).last_durable_observation_at=at;state=await store.commit(current.revision,completed);await hooks.afterExpressionCommit?.(state);
  await writeOutput(output,`${result.reply}\n`);await hooks.afterDisplay?.(state);const displayed=cloneState(state),displayedCognition=findCognition(displayed,cognitionId),displayedAt=nowUtc();displayedCognition.delivery_status="displayed";displayedCognition.last_durable_observation_at=displayedAt;findRuntime(displayed,runtimeId).last_durable_observation_at=displayedAt;state=await store.commit(state.revision,displayed);return {state,providerFailure:null,cognitionId};
}
export function findCognition(state,id){const value=state.operations.cognition_episodes.find(c=>c.cognition_id===id);if(!value)throw new ValidationError(`cognition does not exist: ${id}`);return value;}
function latestRuntime(state){const runtimes=state.operations.runtime_episodes;if(!runtimes.length)return null;const referenced=new Set(runtimes.map(r=>r.recovery_account.previous_runtime).filter(Boolean)),tails=runtimes.filter(r=>!referenced.has(r.runtime_id));if(tails.length!==1)throw new ValidationError("runtime recovery chain has no unique current tail");return tails[0];}
async function writeOutput(output,text){
  if(typeof output==="function"){await output(text);return;}
  await new Promise((resolve,reject)=>{
    let settled=false;
    const finish=(error)=>{if(settled)return;settled=true;if(error){setImmediate(()=>output.off("error",onError));reject(error);}else{output.off("error",onError);resolve();}};
    const onError=error=>finish(error);
    output.once("error",onError);
    try{output.write(text,error=>finish(error));}
    catch(error){finish(error);}
  });
}
