import { ValidationError } from "./errors.mjs";
import { contentDigest, newId, nowUtc, validateState } from "./model.mjs";

export function userEvidence(state, principal, scope, payload, { timestamp = nowUtc() } = {}) {
  requirePrincipal(state, principal);
  const evidence = { evidence_id:newId("evidence"), source_role:"user_command", source_actor:`user:${principal}`, asserted_principal:principal, occurred_at:timestamp, observed_at:timestamp, derived_from_evidence_ids:[], scope, payload_mode:"retained_optional", availability:"available", payload, content_digest:contentDigest(payload) };
  state.evidence.push(evidence); return evidence;
}
function meaning(kind,owner,slot,scope,content,sourceEvidenceId,epistemicRole){
  if(![owner,slot,scope,content].every(v=>typeof v==="string"&&v.trim()))throw new ValidationError("owner, slot, scope, and content must be non-empty"); const at=nowUtc();
  return { meaning_id:newId("meaning"),kind,owner,slot,scope,content,source_evidence_ids:[sourceEvidenceId],epistemic_role:epistemicRole,learned_at:at,applicable_from:at,applicable_until:null,currentness:"current",prospective_lifecycle:"none",supersedes:null,superseded_by:null,uncertainty:null };
}
function ensureNoCurrent(state,kind,owner,slot,scope){if(![owner,slot,scope].every(v=>typeof v==="string"&&v.trim()))throw new ValidationError("owner, slot, and scope must be non-empty");if(state.meanings.some(m=>m.kind===kind&&m.owner===owner&&m.slot===slot&&m.scope===scope&&m.currentness==="current"))throw new ValidationError("a current meaning already occupies this exact semantic slot");}
export function rememberRelationship(state,principal,owner,scope,text){if(owner!==`relationship:${principal}`)throw new ValidationError("relationship owner must match relationship:<principal>");ensureNoCurrent(state,"relationship",owner,"relationship",scope);const ev=userEvidence(state,principal,scope,text);const m=meaning("relationship",owner,"relationship",scope,text,ev.evidence_id,"user_testimony");state.meanings.push(m);validateState(state);return m.meaning_id;}
export function rememberFact(state,principal,owner,slot,scope,text){requireUserOwner(principal,owner);ensureNoCurrent(state,"fact",owner,slot,scope);const ev=userEvidence(state,principal,scope,text);const m=meaning("fact",owner,slot,scope,text,ev.evidence_id,"user_testimony");state.meanings.push(m);validateState(state);return m.meaning_id;}
export function rememberPreference(state,principal,owner,slot,scope,text){requireUserOwner(principal,owner);ensureNoCurrent(state,"preference",owner,slot,scope);const ev=userEvidence(state,principal,scope,text);const m=meaning("preference",owner,slot,scope,text,ev.evidence_id,"user_testimony");state.meanings.push(m);validateState(state);return m.meaning_id;}
export function rememberEpisode(state,principal,slot,owner,scope,summary){if(!["ember",`relationship:${principal}`].includes(owner))throw new ValidationError("episode owner must be ember or relationship:<principal>");ensureNoCurrent(state,"episode_meta",owner,slot,scope);const ev=userEvidence(state,principal,scope,summary);const m=meaning("episode_meta",owner,slot,scope,summary,ev.evidence_id,"user_testimony");state.meanings.push(m);validateState(state);return m.meaning_id;}
export function undertake(state,principal,slot,scope,text){ensureNoCurrent(state,"commitment","ember",slot,scope);const request=userEvidence(state,principal,scope,text),at=nowUtc();const adoption={evidence_id:newId("evidence"),source_role:"ember_adoption",source_actor:"ember",asserted_principal:principal,occurred_at:at,observed_at:at,derived_from_evidence_ids:[request.evidence_id],scope,payload_mode:"descriptor_only"};state.evidence.push(adoption);const m=meaning("commitment","ember",slot,scope,text,adoption.evidence_id,"ember_commitment");m.prospective_lifecycle="live";state.meanings.push(m);validateState(state);return m.meaning_id;}
export function supersede(state,principal,meaningId,text,{reason=null}={}){const old=findMeaning(state,meaningId);if(!["fact","preference"].includes(old.kind))throw new ValidationError("only fact and preference correction/supersession is supported");if(old.currentness!=="current"||old.superseded_by!==null)throw new ValidationError("only a current, unsuperseded meaning can be superseded");requireUserOwner(principal,old.owner);const payload=reason===null?text:`Correction: ${text}\nReason: ${reason}`;const ev=userEvidence(state,principal,old.scope,payload);const next=meaning(old.kind,old.owner,old.slot,old.scope,text,ev.evidence_id,"user_testimony");next.supersedes=old.meaning_id;old.currentness="superseded";old.superseded_by=next.meaning_id;state.meanings.push(next);validateState(state);return next.meaning_id;}
export function attachDetail(state,principal,episodeId,detail){if(typeof detail!=="string"||!detail.trim())throw new ValidationError("optional detail must be non-empty");const episode=findMeaning(state,episodeId);if(episode.kind!=="episode_meta")throw new ValidationError("optional detail can be attached only to episode_meta");if(state.evidence.some(e=>e.related_meaning_id===episodeId))throw new ValidationError("episode already has optional detail evidence");const ev=userEvidence(state,principal,episode.scope,detail);ev.related_meaning_id=episodeId;validateState(state);return ev.evidence_id;}
export function withholdDetail(state,principal,evidenceId,{reason="fixture detail payload unavailable"}={}){requirePrincipal(state,principal);const ev=findEvidence(state,evidenceId);if(ev.related_meaning_id===undefined)throw new ValidationError("fixture fault can withhold only attached episode detail");if(ev.payload_mode!=="retained_optional"||ev.availability!=="available")throw new ValidationError("detail evidence is not currently available");if(reason.toLowerCase().includes("delet"))throw new ValidationError("privacy deletion semantics are unsupported by fixture fault");if(!reason.trim()||reason.includes(ev.payload))throw new ValidationError("unavailability reason must not reveal detail");ev.availability="unavailable";ev.unavailable_reason=reason;delete ev.payload;delete ev.content_digest;const at=nowUtc();const fault={evidence_id:newId("evidence"),source_role:"fixture_fault",source_actor:"runtime",asserted_principal:principal,occurred_at:at,observed_at:at,derived_from_evidence_ids:[evidenceId],scope:ev.scope,payload_mode:"descriptor_only",related_meaning_id:ev.related_meaning_id};state.evidence.push(fault);validateState(state);return fault.evidence_id;}
export function findMeaning(state,id){const value=state.meanings.find(m=>m.meaning_id===id);if(!value)throw new ValidationError(`meaning does not exist: ${id}`);return value;}
export function findEvidence(state,id){const value=state.evidence.find(e=>e.evidence_id===id);if(!value)throw new ValidationError(`evidence does not exist: ${id}`);return value;}
export function requirePrincipal(state,principal){if(principal!==state.runtime_contract.local_principal)throw new ValidationError("asserted principal does not match initialized local principal");}
function requireUserOwner(principal,owner){if(owner!==`user:${principal}`)throw new ValidationError("fact or preference owner must match user:<principal>");}
